version: '3'

services:
  db:
    image: luisclaudiomeca/db-blog-norkon:latest
    container_name: db-norkon
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: wordpress
    volumes:
      - "./dbdata:/var/lib/mysql"
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3306:3306"
    networks:
      - blog-norkon
  wordpress:
    depends_on:
      - db
    image: luisclaudiomeca/wordpress-blog-norkon:latest
    container_name: wordpress-norkon
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: wordpress
    volumes:
      # - hueman:/var/www/html
      - ./theme:/var/www/html
    networks:
      - blog-norkon
  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver-norkon
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./theme:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - blog-norkon

volumes:
  hueman:
  dbdata:


networks:
  blog-norkon:
    driver: bridge
    external: true
